version: 0.2

phases:
  install:
    commands:
      - echo "instalar alguma coisa"
  pre_build:
    commands:
      - echo "pre build"
  build:
    commands:
      - echo "fase build"
      - echo "iniciando o teste"
      - grep -Fq "Congratulations" index.html
  post_build:
    commands:
      - echo "post build"
